### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by rsdoiel** [StefanSchroeder/Golang-NestedDatastructures-Tutorial#1]
I would like to say thank you for the very nice quick reference for simple data structures. What is the license for your tutorial? I would like to fork your tutorial but the Librarians I work with are sure to ask me about license and reuse if I do.

Thanks again,

Robert

**Comment by StefanSchroeder** [comment]
What would you prefer to be able to use it with minimum hassle?

**Comment by rsdoiel** [comment]
Yes, open source licenses are helpful that way.

Thank you,

Robert

**Comment by StefanSchroeder** [comment]
Added MIT license.

**Comment by rsdoiel** [comment]
Thank you,

All the best, Robert
